version: "3"
services:
  ubuntu:
    build:
      context: "./ubuntu"
      args:
        - "USERNAME=anieca"
        - "PASSWORD=anieca"
        - "USER_UID=1000"
        - "PYTHON_VERSION=3.7.7"
    container_name: "Ubuntu"
    ports:
      - "9022:22"
      - "9080:8080"
      - "9081:8081"
      - "9082:8082"
      - "9083:8083"
      - "9084:8084"
    volumes:
      - "./share:/share"
    privileged: true
